const express=require('express')
const cors=require('cors')
const dotenv=require('dotenv')
const defaultRoute=require('./comps/default')
const coursesRoute=require('./comps/courses')
const app=express()
dotenv.config()
app.use(cors())
app.get('/',defaultRoute.route)
app.get('/courses',coursesRoute.route)
app.listen(process.env.PORT,()=>{
    console.log("shreepad shree vallabh is blessing you on port "+process.env.PORT)
})